faiss_db:
  collection_name: "document_portal"


embedding_model:
  provider: "google"
  embedding_model_name: "models/text-embedding-004"

retriever:
  top_k: 10

LLMs:
  groq:
    provider: "groq"
    llm_model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    llm_model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048
